apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/docker-default: "true"
        io.kompose.service: app
    spec:
      containers:
        - image: eclipse-temurin:17-jdk
          name: app
          ports:
            - containerPort: 8080
            #  hostPort: 8080
              protocol: TCP
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /app
              name: app-claim0
          workingDir: /app
      restartPolicy: Always
      volumes:
        - name: app-claim0
          persistentVolumeClaim:
            claimName: app-claim0
status: {}
