apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-map
data:
  mysql-server: db    # The name of mysql service
  mysql-database-name: dbcow     # The name of the database used by the demo app
  mysql-user-username: user     # A new created user for the demo app 