services:
  app:
    image: eclipse-temurin:17-jdk
    container_name: app
    env_file:
      - ./mysql/db.env # mysqlと同じものを指定
    tty: true
    working_dir: /app
    volumes:
      - ../app:/app # Spring Bootのプロジェクト
    ports:
      - 8080:8080 # 通常実行
      - 5050:5050 # デバッグ用
    depends_on:
      - db # 「mysql」の後で起動

  db:
    image: mysql:5.7
    container_name: db
    env_file:
      - ./mysql/db.env # MySQL設定ファイル
    volumes:
      #- ./mysql/data:/var/lib/mysql # 実データの永続化
      #- ./mysql/log:/var/log/mysql # logの永続化
      - ../app/src/main/resources/:/docker-entrypoint-initdb.d # 初期SQL
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
